"""added timestamp to the vehicle position

Revision ID: 79c98cc7dabc
Revises: 2aa1874dd408
Create Date: 2016-12-07 20:55:16.053071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79c98cc7dabc'
down_revision = '2aa1874dd408'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_positions', sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle_positions', 'timestamp')
    # ### end Alembic commands ###
